channels:
- conda-forge
dependencies:
- python=3.12.8
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - pandas==2.2.3
  - psutil==5.9.8
  - scikit-learn==1.6.0
  - scipy==1.15.0
name: mlflow-env
