name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Start MLflow Server
      run: |
        nohup mlflow server \
          --backend-store-uri sqlite:///mlflow.db \
          --default-artifact-root ./artifacts \
          --host 127.0.0.1 \
          --port 5000 &
        sleep 10  # Donne du temps au serveur pour démarrer

    - name: Verify MLflow Server is Running
      run: |
        curl -f http://127.0.0.1:5000/api/2.0/mlflow/ || exit 1

    - name: Run Tests
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry run pytest tests/


  deploy:
    needs: build
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t fastapi-api .

    - name: Push Docker Image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag fastapi-api:latest chancella/fastapi-api:latest
        docker push chancella/fastapi-api:latest

